# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.2.4
group=logictechcorp.netherex
java_version=25

# Common
minecraft_version=26.1.2
mod_name=NetherEx
mod_author=LogicTechCorp
mod_id=netherex
mod_changelog_file=changelog.md
license=Code: MIT | Assets: MIT and ARR (See GitHub README.md for more info)
credits=Fish2, Eleazzaar, Nazenn, Angelz/Demonly, Vlakk, AnarchCassius, LapisWhovian, misterslime, Vivi, Cameron, rye, SnakeBlock, hatsondogs, Endergy, Farcr, Adeline, SirBaconFace, Yapetto, enri, crispytwig, Nitpick/Olive, ZucchiniByDay, JadenXgamer, and Jamiscus
description=NetherEx is a Nether content mod for Minecraft.

# This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
minecraft_version_range=[26.1.2]

# Fabric
fabric_version=0.155.2+26.1.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.1.2.82
neoforge_loader_version_range=[4,)

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Dependencies
regutils_version=26.1-0.1.0
terrablender_version=26.1.2.0.3
geckolib_version=5.5.2
resourcefulconfig_minecraft_version=26.1
resourcefulconfig_version=4.0.1

# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# CurseForge/CurseForge Gradle
curseforge_gradle_version=1.3.+
curseforge_project=248039
curseforge_page=https://www.curseforge.com/minecraft/mc-mods/netherex

# Minotaur/Modrinth
minotaur_version=2.+
modrinth_project=2PIVd4Ik
modrinth_page=https://modrinth.com/mod/netherex
